# Julia Syntax Tutorial

Everything covered today (and **even more**) can be found [here](http://docs.julialang.org/en/release-0.5/manual/).

In [1]:
# Variables

x = 3 
x = 3.0
string = "Hello world!"
character = 'a'
δ = 1e-5

pi
e
α̂₁ = pi / 2

1.5707963267948966

In [2]:
# Arrays

u = [1 3 5 7]
v = ones(4)
w = Array{Float64}(2)

X = rand(4, 4)
I = eye(4)
column = [1,2,3]
row = [1 2 3]
A = [1 2 3; 4 5 6; 7 8 9]
b = [[1 2 3] [4 5 6] [7 8 9]]
B = reshape(b, 3, 3)
C = fill(15, 2, 3)

length(A)
ndims(A)
size(A)

(3, 3)

In [3]:
# Array indexing and assignment

A[3, 1]
A[1,:]
A[1:2, 2:end]
A[2, [1 3]]

A[1:2, 2:3] = -1
A[3, 1:2] = [10 11]


1×2 Array{Int64,2}:
 10  11

In [4]:
# Mathematical operations

2 + 5
3.5 ^ 2
[1 2] + [2 3]
[1 2] * 1.5
A[1, :]' * ones(3)
A .* B

3×3 Array{Int64,2}:
  1  -4  -7
  8  -5  -8
 30  66  81

In [5]:
# inequalities

3.0 > 2.0
9 ≤ 9 
1 != 2
[1 2] .< [2 3]

1×2 BitArray{2}:
 true  true

In [6]:
# Control flow (and string interpolation!)
x = -Inf
y = 1
if x < y
    println("x is less than y: $x < $y")
elseif x > y
  println("x is greater than y: $x > $y")
else
  println("x is equal to y: $x = $y")
end

x is less than y: -Inf < 1


In [7]:
i = 1
while i <= 5
    println(i)
    i += 1 
end

1
2
3
4
5


In [8]:
for i = 1:5
    if i == 3
        # `continue` skips to the next iteration in the for-loop;
        # `break` breaks out of the enclosing for-loop
        # continue
        break
    end
    println(i)
end

1
2


In [9]:
u = [1,3,5,7]
for i in u
    println(i)
end

1
3
5
7


# functions

In [10]:
# these three syntaxes all define the function f(x) = 2x
inline_f(x) = 2*x

function f(x::Float64)::Float64
    return 2*x
end

x -> 2*x

(::#1) (generic function with 1 method)

In [11]:
f(3.0)

6.0

In [12]:
# default values for positional arguments
function f(x, mult=2)
    return mult*x
end
@show f(2)    # ==4
@show f(2, 3) # ==6

f(2) = 4
f(2, 3) = 6


6

In [13]:
# default values for keyword arguments: use a semicolon instead of a comma
function f(x; mult=2)
    return mult*x
end
@show f(2)         # ==4
@show f(2, mult=3) # ==6

f(2) = 4
f(2, mult=3) = 6


In [14]:
# variable number of arguments
function f(x...)
    for xi in x
        println(xi)
    end
end
f(1,2,3,4,"a","b","c")

1
2
3
4
a
b
c


In [15]:
# list comprehensions: shorthand for loops (not very memory efficient)
[x^2 for x in 1:5]
[x^2 for x in 1:5 if x>2]
[x^k for x in 1:10 for k in 1:5]

50-element Array{Int64,1}:
      1
      1
      1
      1
      1
      2
      4
      8
     16
     32
      3
      9
     27
      ⋮
   4096
  32768
      9
     81
    729
   6561
  59049
     10
    100
   1000
  10000
 100000

In [16]:
# dictionaries and sets

x = Set([1,2,3,3,4,1])
y = Set([1,5])
union(x, y)
intersect(x, y)

d = Dict()
d[4] = 7
d['a'] = 2
@show d[4]

d[4] = 7


7

# Types and multiple dispatch

In [17]:
# x::y is an assertion that x is a variable of type y

1.0::Float64

1.0

In [18]:
# if we assert something false, we get a type error 
1.0::Int

LoadError: TypeError: typeassert: expected Int64, got Float64

In [19]:
# we can define many functions with the same name, which call arguments of different types
# julia decides which to call by looking at the type of the argument

f(x::Int) = println("$x is an integer")
f(x::Float64) = println("$x is an float")
f(2)
f(2.0)

2 is an integer


In [20]:
type Student
    name::String    
    gpa::Float64
end

s1 = Student("Alice", 3.9)
s2 = Student("Bob", 3.2)

Student("Bob", 3.2)

In [21]:
s1.name

"Alice"

In [22]:
f(s::Student) = println("$(s.name) has a $(s.gpa) gpa")

# we've defined the "f" function on three different types
# julia knows to call the right one by looking at the type of the argument

f(s1)
f(s2)
f(4)
f(sqrt(2))

Alice has a 3.9 gpa


In [23]:
methods(f)

# 6 methods for generic function "f":
f(s::Student) in Main at In[22]:1
f(x::Float64) in Main at In[19]:5
f(x::Int64) in Main at In[19]:4
f(x; mult) in Main at In[13]:3
f(x, mult) in Main at In[12]:3
f(x...) in Main at In[14]:3